import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://www.roboform.com/filling-test-all-fields")
    await page.locator("input[name=\"\\30 1___title\"]").click()
    await page.locator("input[name=\"\\30 1___title\"]").fill("grgg")
    await page.locator("input[name=\"\\30 2frstname\"]").click()
    await page.locator("input[name=\"\\30 2frstname\"]").fill("rgerggr")
    await page.locator("input[name=\"\\30 3middle_i\"]").click()
    await page.locator("input[name=\"\\30 3middle_i\"]").fill("greg")
    await page.locator("input[name=\"\\30 4lastname\"]").click()
    await page.locator("input[name=\"\\30 4lastname\"]").fill("gergrg")
    await page.locator("input[name=\"\\30 4fullname\"]").click()
    await page.locator("input[name=\"\\30 4fullname\"]").fill("grege")
    await page.locator("input[name=\"\\30 5_company\"]").click()
    await page.locator("input[name=\"\\30 5_company\"]").fill("gergerg")
    await page.locator("input[name=\"\\30 6position\"]").click()
    await page.locator("input[name=\"\\30 6position\"]").fill("gergerg")
    await page.locator("input[name=\"\\31 0address1\"]").click()
    await page.locator("input[name=\"\\31 0address1\"]").fill("ergrgre")
    await page.locator("input[name=\"\\31 1address2\"]").click()
    await page.locator("input[name=\"\\31 1address2\"]").fill("gergre")
    await page.locator("input[name=\"\\31 3adr_city\"]").click()
    await page.locator("input[name=\"\\31 3adr_city\"]").fill("gergergg")
    await page.locator("input[name=\"\\31 4adrstate\"]").click()
    await page.locator("input[name=\"\\31 4adrstate\"]").fill("erg")
    await page.locator("input[name=\"\\31 5_country\"]").click()
    await page.locator("input[name=\"\\31 5_country\"]").fill("gerger")
    await page.locator("input[name=\"\\31 6addr_zip\"]").click()
    await page.locator("input[name=\"\\31 6addr_zip\"]").fill("78955")
    await page.locator("input[name=\"\\32 0homephon\"]").click()
    await page.locator("input[name=\"\\32 0homephon\"]").fill("78445555")
    await page.locator("input[name=\"\\32 1workphon\"]").click()
    await page.locator("input[name=\"\\32 1workphon\"]").fill("512445444")
    await page.locator("input[name=\"\\32 2faxphone\"]").click()
    await page.locator("input[name=\"\\32 2faxphone\"]").fill("45141555")
    await page.locator("input[name=\"\\32 3cellphon\"]").click()
    await page.locator("input[name=\"\\32 3cellphon\"]").fill("456456464")
    await page.locator("input[name=\"\\32 4emailadr\"]").click()
    await page.locator("input[name=\"\\32 4emailadr\"]").fill("hrguei@gmail.com")
    await page.locator("input[name=\"\\32 5web_site\"]").click()
    await page.locator("input[name=\"\\32 5web_site\"]").fill("www.test.com")
    await page.locator("input[name=\"\\33 0_user_id\"]").click()
    await page.locator("input[name=\"\\33 0_user_id\"]").fill("jbdfhkjdg")
    await page.locator("input[name=\"\\33 1password\"]").click()
    await page.locator("input[name=\"\\33 1password\"]").fill("gdfhigohg")
    await page.locator("select[name=\"\\34 0cc__type\"]").select_option("9")
    await page.locator("input[name=\"\\34 1ccnumber\"]").click()
    await page.locator("input[name=\"\\34 1ccnumber\"]").fill("45544444544454")
    await page.locator("input[name=\"\\34 3cvc\"]").click()
    await page.locator("input[name=\"\\34 3cvc\"]").fill("123")
    await page.locator("select[name=\"\\34 2ccexp_mm\"]").select_option("3")
    await page.locator("select[name=\"\\34 3ccexp_yy\"]").select_option("2021")
    await page.locator("input[name=\"\\34 4cc_uname\"]").click()
    await page.locator("input[name=\"\\34 4cc_uname\"]").fill("hug")
    await page.locator("input[name=\"\\34 5ccissuer\"]").click()
    await page.locator("input[name=\"\\34 5ccissuer\"]").fill("hugbiug")
    await page.locator("input[name=\"\\34 6cccstsvc\"]").click()
    await page.locator("input[name=\"\\34 6cccstsvc\"]").fill("ghg")
    await page.locator("input[name=\"\\36 0pers_sex\"]").click()
    await page.locator("input[name=\"\\36 0pers_sex\"]").fill("yes")
    await page.locator("input[name=\"\\36 1pers_ssn\"]").click()
    await page.locator("input[name=\"\\36 1pers_ssn\"]").fill("45612345")
    await page.locator("input[name=\"\\36 2driv_lic\"]").click()
    await page.locator("input[name=\"\\36 2driv_lic\"]").fill("4587997979")
    await page.locator("select[name=\"\\36 6mm\"]").select_option("1")
    await page.locator("select[name=\"\\36 7dd\"]").select_option("1")
    await page.locator("select[name=\"\\36 8yy\"]").select_option("1920")
    await page.locator("input[name=\"\\36 6pers_age\"]").click()
    await page.locator("input[name=\"\\36 6pers_age\"]").fill("21")
    await page.locator("input[name=\"\\36 7birth_pl\"]").click()
    await page.locator("input[name=\"\\36 7birth_pl\"]").fill("Tx")
    await page.locator("input[name=\"\\36 8__income\"]").click()
    await page.locator("input[name=\"\\36 8__income\"]").fill("2000000")
    await page.locator("input[name=\"\\37 1__custom\"]").click()
    await page.locator("input[name=\"\\37 1__custom\"]").fill("thankyoy")
    await page.locator("input[name=\"\\37 2__commnt\"]").click()
    await page.locator("input[name=\"\\37 2__commnt\"]").fill("letgo")
    await page.locator("div").filter(has_text="Title First Name Middle").nth(1).click()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
