import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://www.roboform.com/filling-test-all-fields")
    await page.locator("input[name=\"\\30 1___title\"]").click()
    await page.locator("input[name=\"\\30 1___title\"]").fill("sdfsf")
    await page.locator("input[name=\"\\30 2frstname\"]").click()
    await page.locator("input[name=\"\\30 2frstname\"]").fill("fdfsf")
    await page.locator("input[name=\"\\30 3middle_i\"]").click()
    await page.locator("input[name=\"\\30 3middle_i\"]").fill("fdffs")
    await page.locator("input[name=\"\\30 4lastname\"]").click()
    await page.locator("input[name=\"\\30 4lastname\"]").fill("fsdfs")
    await page.locator("input[name=\"\\30 4fullname\"]").click()
    await page.locator("input[name=\"\\30 4fullname\"]").fill("fsdfs")
    await page.locator("input[name=\"\\30 5_company\"]").click()
    await page.locator("input[name=\"\\30 5_company\"]").fill("fdssf")
    await page.locator("input[name=\"\\30 6position\"]").click()
    await page.locator("input[name=\"\\30 6position\"]").fill("fsdfd")
    await page.locator("input[name=\"\\31 0address1\"]").click()
    await page.locator("input[name=\"\\31 0address1\"]").fill("fsfsf")
    await page.locator("input[name=\"\\31 1address2\"]").click()
    await page.locator("input[name=\"\\31 1address2\"]").fill("fsfdf")
    await page.locator("input[name=\"\\31 3adr_city\"]").click()
    await page.locator("input[name=\"\\31 3adr_city\"]").fill("fsfsfs")
    await page.locator("input[name=\"\\31 4adrstate\"]").click()
    await page.locator("input[name=\"\\31 4adrstate\"]").fill("fsdfdfs")
    await page.locator("input[name=\"\\31 5_country\"]").click()
    await page.locator("input[name=\"\\31 5_country\"]").fill("fsfdf")
    await page.locator("input[name=\"\\31 6addr_zip\"]").click()
    await page.locator("input[name=\"\\31 6addr_zip\"]").fill("fsfsf")
    await page.locator("input[name=\"\\32 0homephon\"]").click()
    await page.locator("input[name=\"\\32 0homephon\"]").fill("sfsfs")
    await page.locator("input[name=\"\\32 1workphon\"]").click()
    await page.locator("input[name=\"\\32 1workphon\"]").fill("sfsfs")
    await page.locator("input[name=\"\\32 2faxphone\"]").click()
    await page.locator("input[name=\"\\32 2faxphone\"]").fill("fsfsf")
    await page.locator("input[name=\"\\32 3cellphon\"]").click()
    await page.locator("input[name=\"\\32 3cellphon\"]").fill("fsdfsfs")
    await page.locator("input[name=\"\\32 4emailadr\"]").click()
    await page.locator("input[name=\"\\32 4emailadr\"]").fill("sffs")
    await page.locator("input[name=\"\\32 5web_site\"]").click()
    await page.locator("input[name=\"\\32 5web_site\"]").fill("fsfsfs")
    await page.locator("input[name=\"\\37 2__commnt\"]").click()
    await page.locator("input[name=\"\\37 2__commnt\"]").fill("fsdfsf")
    await page.locator("input[name=\"\\37 1__custom\"]").click()
    await page.locator("input[name=\"\\37 1__custom\"]").fill("sdfsdf")
    await page.locator("input[name=\"\\36 8__income\"]").click()
    await page.locator("input[name=\"\\36 8__income\"]").fill("sfsdfs")
    await page.locator("input[name=\"\\36 7birth_pl\"]").click()
    await page.locator("input[name=\"\\36 7birth_pl\"]").fill("sfsfsff")
    await page.locator("input[name=\"\\36 6pers_age\"]").click()
    await page.locator("input[name=\"\\36 6pers_age\"]").fill("43")
    await page.locator("select[name=\"\\36 6mm\"]").select_option("1")
    await page.locator("select[name=\"\\36 7dd\"]").select_option("1")
    await page.locator("select[name=\"\\36 8yy\"]").select_option("1920")
    await page.locator("input[name=\"\\36 2driv_lic\"]").click()
    await page.locator("input[name=\"\\36 2driv_lic\"]").fill("423432434")
    await page.locator("input[name=\"\\36 1pers_ssn\"]").click()
    await page.locator("input[name=\"\\36 1pers_ssn\"]").fill("42343243")
    await page.locator("input[name=\"\\36 0pers_sex\"]").click()
    await page.locator("input[name=\"\\36 0pers_sex\"]").fill("male")
    await page.locator("input[name=\"\\34 6cccstsvc\"]").click()
    await page.locator("input[name=\"\\34 6cccstsvc\"]").fill("gfhgfhhg")
    await page.locator("input[name=\"\\34 5ccissuer\"]").click()
    await page.locator("input[name=\"\\34 5ccissuer\"]").fill("fghgfh")
    await page.locator("input[name=\"\\34 4cc_uname\"]").click()
    await page.locator("input[name=\"\\34 4cc_uname\"]").fill("fghgfhg")
    await page.locator("select[name=\"\\34 2ccexp_mm\"]").select_option("2")
    await page.locator("select[name=\"\\34 3ccexp_yy\"]").select_option("2020")
    await page.locator("input[name=\"\\34 3cvc\"]").click()
    await page.locator("input[name=\"\\34 3cvc\"]").fill("hfghg")
    await page.locator("input[name=\"\\34 1ccnumber\"]").click()
    await page.locator("input[name=\"\\34 1ccnumber\"]").fill("hfghgfh")
    await page.locator("input[name=\"\\33 1password\"]").click()
    await page.locator("input[name=\"\\33 1password\"]").fill("hffghfh")
    await page.locator("input[name=\"\\33 0_user_id\"]").click()
    await page.locator("input[name=\"\\33 0_user_id\"]").fill("hgfhh")
    await page.locator("select[name=\"\\34 0cc__type\"]").select_option("9")

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
